name: "Setup Polkadot chain-spec-builder"
description: "Installs and configures Polkadot chain-spec-builder"

inputs:
  chain-spec-builder-version:
    description: "Polkadot chain-spec-builder version"
    required: true

outputs:
  version:
    description: "Installed chain-spec-builder version"
    value: ${{ steps.verify.outputs.version }}
  binary-path:
    description: "Path to chain-spec-builder binary"
    value: ${{ steps.verify.outputs.path }}
  cache-hit:
    description: "Whether binary cache was hit"
    value: ${{ steps.cache.outputs.cache-hit }}

runs:
  using: "composite"
  steps:
    - name: Validate inputs
      shell: bash
      run: |
        if [[ ! "${{ inputs.chain-spec-builder-version }}" =~ ^[0-9]+\.[0-9]+\.[0-9]+$ ]]; then
          echo "❌ Invalid version format: ${{ inputs.chain-spec-builder-version }}"
          echo "Expected format: X.Y.Z (e.g., 10.0.0)"
          exit 1
        fi

    - name: Cache chain-spec-builder binary
      id: cache
      uses: actions/cache@v4
      with:
        path: ~/.cargo/bin
        key: ${{ runner.os }}-${{ runner.arch }}-chain-spec-builder-${{ inputs.chain-spec-builder-version }}

    - name: Install chain-spec-builder
      if: steps.cache.outputs.cache-hit != 'true'
      shell: bash
      run: |
        echo "🔧 Installing chain-spec-builder@${{ inputs.chain-spec-builder-version }}..."
        
        if command -v chain-spec-builder >/dev/null 2>&1; then
          INSTALLED_VERSION=$(chain-spec-builder --version | awk '{print $2}')
          if [ "$INSTALLED_VERSION" = "${{ inputs.chain-spec-builder-version }}" ]; then
            echo "✅ chain-spec-builder $INSTALLED_VERSION already installed, skipping"
            exit 0
          else
            echo "⚠️ Different version found ($INSTALLED_VERSION), installing requested version..."
          fi
        fi

        cargo install staging-chain-spec-builder --version ${{ inputs.chain-spec-builder-version }} --locked --force
        echo "✅ Installation completed"

    - name: Add Cargo bin to PATH
      shell: bash
      run: echo "${HOME}/.cargo/bin" >> $GITHUB_PATH

    - name: Verify installation
      id: verify
      shell: bash
      run: |
        echo "🔍 Verifying chain-spec-builder installation..."
        
        if ! command -v chain-spec-builder &> /dev/null; then
          echo "❌ chain-spec-builder not found in PATH"
          exit 1
        fi
        
        VERSION_OUTPUT=$(chain-spec-builder --version | awk '{print $2}')
        BINARY_PATH=$(which chain-spec-builder)
        
        echo "✅ chain-spec-builder found at: $BINARY_PATH"
        echo "✅ Version: $VERSION_OUTPUT"
        
        echo "version=$VERSION_OUTPUT" >> $GITHUB_OUTPUT
        echo "path=$BINARY_PATH" >> $GITHUB_OUTPUT
        
        echo "🧪 Testing basic functionality..."
        if chain-spec-builder --help > /dev/null 2>&1; then
          echo "✅ chain-spec-builder is working correctly"
        else
          echo "❌ chain-spec-builder failed basic functionality test"
          exit 1
        fi
