name: "Setup Kitchensink Parachain"
description: "Clones, builds, and caches the kitchensink parachain from polkadot-docs-tests repository"

inputs:
  branch:
    description: "Branch to clone"
    required: false
    default: "master"
  cache-key-suffix:
    description: "Suffix for build cache key"
    required: false
    default: ""

outputs:
  parachain-path:
    description: "Path to cloned parachain"
    value: ${{ steps.setup.outputs.template-path }}
  runtime-path:
    description: "Path to WASM runtime file"
    value: ${{ steps.setup.outputs.runtime-path }}
  cache-hit:
    description: "Whether build cache was hit"
    value: ${{ steps.build-cache.outputs.cache-hit }}

runs:
  using: "composite"
  steps:
    - name: Setup template and paths
      id: setup
      shell: bash
      run: |
        PARACHAIN_PATH="${GITHUB_WORKSPACE}/kitchensink-parachain"
        RUNTIME_PATH="${PARACHAIN_PATH}/target/release/wbuild/parachain-template-runtime/parachain_template_runtime.compact.compressed.wasm"
        
        echo "parachain-path=$PARACHAIN_PATH" >> $GITHUB_OUTPUT
        echo "runtime-path=$RUNTIME_PATH" >> $GITHUB_OUTPUT

    - name: Clone kitchensink-parachain parachain
      shell: bash
      run: |
        echo "📥 Cloning kitchensink-parachain from https://github.com/polkadot-developers/polkadot-docs-tests (branch: ${{ inputs.branch }})..."
        
        if [ -d "kitchensink-parachain" ]; then
          echo "🧹 Cleaning existing template directory..."
          rm -rf kitchensink-parachain
        fi
        
        # Clone with sparse checkout to get only the kitchensink-parachain directory
        git clone --no-checkout --branch ${{ inputs.branch }} https://github.com/polkadot-developers/polkadot-docs-tests temp-repo
        cd temp-repo
        git sparse-checkout init --cone
        git sparse-checkout set kitchensink-parachain
        git checkout
        
        # Move the kitchensink-parachain to the workspace root
        mv kitchensink-parachain ../kitchensink-parachain
        cd ..
        rm -rf temp-repo
        
        echo "✅ Template cloned successfully"
        
        # Verify critical files exist
        if [ ! -f "kitchensink-parachain/Cargo.toml" ]; then
          echo "❌ Cargo.toml not found in template"
          exit 1
        fi

    - name: Cache build artifacts
      id: build-cache
      uses: actions/cache@v4
      with:
        path: |
          kitchensink-parachain/target/release
          kitchensink-parachain/target/wbuild
        key: parachain-build-${{ runner.os }}-${{ runner.arch }}-${{ hashFiles('https://github.com/polkadot-developers/polkadot-docs-tests') }}-${{ inputs.branch }}-${{ hashFiles('kitchensink-parachain/**/Cargo.toml', 'kitchensink-parachain/**/Cargo.lock') }}${{ inputs.cache-key-suffix }}
        restore-keys: |
          parachain-build-${{ runner.os }}-${{ runner.arch }}-${{ hashFiles('https://github.com/polkadot-developers/polkadot-docs-tests') }}-${{ inputs.branch }}-
          parachain-build-${{ runner.os }}-${{ runner.arch }}-${{ hashFiles('https://github.com/polkadot-developers/polkadot-docs-tests') }}-${{ inputs.branch }}-

    - name: Build parachain
      if: steps.build-cache.outputs.cache-hit != 'true'
      working-directory: kitchensink-parachain
      shell: bash
      run: |
        echo "🔨 Building kitchensink-parachain parachain..."
        echo "📊 Available disk space:"
        df -h
        
        # Set build optimizations
        export CARGO_PROFILE_RELEASE_LTO=thin
        export CARGO_PROFILE_RELEASE_CODEGEN_UNITS=1
        
        # Build with progress and error handling
        cargo build --release --locked --verbose
        
        echo "✅ Build completed successfully"
        
        echo "📊 Final disk space:"
        df -h

    - name: Verify build artifacts
      shell: bash
      run: |
        echo "🔍 Verifying build artifacts..."
        
        RUNTIME_PATH="${{ steps.setup.outputs.runtime-path }}"
        
        # Check runtime
        if [ ! -f "$RUNTIME_PATH" ]; then
          echo "❌ Runtime WASM not found at: $RUNTIME_PATH"
          echo "🔍 Available runtime files:"
          find kitchensink-parachain/target -name "*.wasm" -type f || echo "No WASM files found"
          exit 1
        fi
        
        # Check file sizes
        RUNTIME_SIZE=$(du -h "$RUNTIME_PATH" | cut -f1)
        
        echo "✅ Runtime verified: $RUNTIME_SIZE"