name: "Setup Polkadot omni-node"
description: "Installs and configures Polkadot omni-node"

inputs:
  omni-node-version:
    description: "Polkadot omni-node version"
    required: true

outputs:
  version:
    description: "Installed omni-node version"
    value: ${{ steps.verify.outputs.version }}
  binary-path:
    description: "Path to polkadot-omni-node binary"
    value: ${{ steps.verify.outputs.path }}
  cache-hit:
    description: "Whether binary cache was hit"
    value: ${{ steps.cache.outputs.cache-hit }}

runs:
  using: "composite"
  steps:
    - name: Validate inputs
      shell: bash
      run: |
        if [[ ! "${{ inputs.omni-node-version }}" =~ ^[0-9]+\.[0-9]+\.[0-9]+$ ]]; then
          echo "❌ Invalid version format: ${{ inputs.omni-node-version }}"
          echo "Expected format: X.Y.Z (e.g., 0.5.0)"
          exit 1
        fi

    - name: Cache omni-node binary
      id: cache
      uses: actions/cache@v4
      with:
        path: ~/.cargo/bin
        key: ${{ runner.os }}-${{ runner.arch }}-omni-node-${{ inputs.omni-node-version }}

    - name: Install Polkadot omni-node
      if: steps.cache.outputs.cache-hit != 'true'
      shell: bash
      run: |
        echo "🔧 Installing polkadot-omni-node@${{ inputs.omni-node-version }}..."
        
        if command -v polkadot-omni-node >/dev/null 2>&1; then
          INSTALLED_VERSION=$(polkadot-omni-node --version | awk '{print $2}')
          if [ "$INSTALLED_VERSION" = "${{ inputs.omni-node-version }}" ]; then
            echo "✅ polkadot-omni-node $INSTALLED_VERSION already installed, skipping"
            exit 0
          else
            echo "⚠️ Different version found ($INSTALLED_VERSION), installing requested version..."
          fi
        fi
        
        cargo install polkadot-omni-node --version ${{ inputs.omni-node-version }} --locked --force
        echo "✅ Installation completed"

    - name: Add Cargo bin to PATH
      shell: bash
      run: echo "${HOME}/.cargo/bin" >> $GITHUB_PATH

    - name: Verify installation
      id: verify
      shell: bash
      run: |
        echo "🔍 Verifying polkadot-omni-node installation..."
        
        if ! command -v polkadot-omni-node &> /dev/null; then
          echo "❌ polkadot-omni-node not found in PATH"
          exit 1
        fi
        
        VERSION_OUTPUT=$(polkadot-omni-node --version | awk '{print $2}')
        BINARY_PATH=$(which polkadot-omni-node)
        
        echo "✅ polkadot-omni-node found at: $BINARY_PATH"
        echo "✅ Version: $VERSION_OUTPUT"
        
        echo "version=$VERSION_OUTPUT" >> $GITHUB_OUTPUT
        echo "path=$BINARY_PATH" >> $GITHUB_OUTPUT
        
        echo "🧪 Testing basic functionality..."
        if polkadot-omni-node --help > /dev/null 2>&1; then
          echo "✅ polkadot-omni-node is working correctly"
        else
          echo "❌ polkadot-omni-node failed basic functionality test"
          exit 1
        fi
