## Zombienet config using template node (placeholder)
[settings]
relay_chain = "paseo"
para_id = 1000

[nodes.relay]
name = "relay"
command = "polkadot"

[nodes.parachain]
name = "para"
command = "parachain-template-node"
args = ["--dev"]

