name: Build a Parachain

on:
  workflow_dispatch:
    inputs:
      template-repo:
        description: "Repository URL for the parachain template"
        required: false
        default: "https://github.com/paritytech/polkadot-sdk-parachain-template.git"
        type: string
      template-branch:
        description: "Branch of a parachain template to clone"
        required: false
        default: "main"
        type: string
      chain-spec-builder-version:
        description: 'Polkadot chain-spec-builder version'
        default: '10.0.0'
        required: false
        type: string
      omni-node-version:
        description: 'Polkadot omni-node version'
        default: '0.5.0'
        required: false
        type: string
      para-id:
        description: 'Parachain ID'
        default: '1000'
        required: false
        type: string
      relay-chain:
        description: 'Relay chain to use'
        default: 'paseo'
        required: false
        type: choice
        options:
          - "paseo"
          - "westend"
      run-duration:
        description: 'How long to run the node (in seconds, 0 for indefinite)'
        default: '120'
        required: false
        type: string

env:
  RUST_VERSION: "1.86"

jobs:
  # Parallel setup jobs for better performance
  setup-tools:
    name: Setup Tools
    runs-on: ubuntu-latest
    outputs:
      chain-spec-builder-version: ${{ steps.chain-spec.outputs.version }}
      omni-node-version: ${{ steps.omni-node.outputs.version }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup chain-spec-builder
        id: chain-spec
        uses: ./.github/actions/setup-chain-spec-builder
        with:
          chain-spec-builder-version: ${{ inputs.chain-spec-builder-version }}
          rust-version: ${{ env.RUST_VERSION }}

      - name: Setup omni-node
        id: omni-node
        uses: ./.github/actions/setup-omni-node
        with:
          omni-node-version: ${{ inputs.omni-node-version }}
          rust-version: ${{ env.RUST_VERSION }}

      - name: Verify binaries before caching
        run: |
          echo "🔍 Checking installed binaries..."
          ls -la ~/.cargo/bin/ || echo "~/.cargo/bin/ does not exist"
          
          if [ -f ~/.cargo/bin/chain-spec-builder ]; then
            echo "✅ chain-spec-builder found"
            ls -la ~/.cargo/bin/chain-spec-builder
          else
            echo "❌ chain-spec-builder not found"
          fi
          
          if [ -f ~/.cargo/bin/polkadot-omni-node ]; then
            echo "✅ polkadot-omni-node found"
            ls -la ~/.cargo/bin/polkadot-omni-node
          else
            echo "❌ polkadot-omni-node not found"
          fi

      - name: Cache tools for main job
        uses: actions/cache/save@v4
        if: hashFiles('~/.cargo/bin/chain-spec-builder') != '' && hashFiles('~/.cargo/bin/polkadot-omni-node') != ''
        with:
          path: |
            ~/.cargo/bin/chain-spec-builder
            ~/.cargo/bin/polkadot-omni-node
          key: tools-${{ runner.os }}-${{ runner.arch }}-${{ inputs.chain-spec-builder-version }}-${{ inputs.omni-node-version }}

  build-parachain:
    name: Build Parachain
    runs-on: ubuntu-latest
    outputs:
      template-path: ${{ steps.setup-template.outputs.template-path }}
      runtime-path: ${{ steps.setup-template.outputs.runtime-path }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup parachain template
        id: setup-template
        uses: ./.github/actions/setup-parachain-template
        with:
          template-repo: ${{ inputs.template-repo }}
          template-branch: ${{ inputs.template-branch }}
          rust-version: ${{ env.RUST_VERSION }}
          para-id: ${{ inputs.para-id }}

      - name: Upload parachain artifacts
        uses: actions/upload-artifact@v4
        with:
          name: parachain-artifacts-${{ github.run_id }}
          path: |
            ${{ steps.setup-template.outputs.binary-path }}
            ${{ steps.setup-template.outputs.runtime-path }}
          retention-days: 1

  run-parachain:
    name: Run Parachain Node
    runs-on: ubuntu-latest
    needs: [setup-tools, build-parachain]
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Validate inputs
        run: |
          if [[ ! "${{ inputs.para-id }}" =~ ^[0-9]+$ ]]; then
            echo "❌ Invalid para-id: ${{ inputs.para-id }}"
            exit 1
          fi
          
          if [[ ! "${{ inputs.run-duration }}" =~ ^[0-9]+$ ]]; then
            echo "❌ Invalid run-duration: ${{ inputs.run-duration }}"
            exit 1
          fi
          
          # Validate repository URL format
          if [[ ! "${{ inputs.template-repo }}" =~ ^https://github\.com/.+/.+\.git$ ]]; then
            echo "⚠️ Warning: template-repo '${{ inputs.template-repo }}' doesn't follow expected GitHub format"
          fi
          
          echo "✅ Using template repository: ${{ inputs.template-repo }}"
          echo "✅ Using template branch: ${{ inputs.template-branch }}"

      - name: Restore tools cache
        uses: actions/cache/restore@v4
        with:
          path: ~/.cargo/bin
          key: tools-${{ runner.os }}-${{ runner.arch }}-${{ inputs.chain-spec-builder-version }}-${{ inputs.omni-node-version }}
          fail-on-cache-miss: true

      - name: Download parachain artifacts
        uses: actions/download-artifact@v4
        with:
          name: parachain-artifacts-${{ github.run_id }}
          path: ./artifacts

      - name: Setup paths and permissions
        run: |
          # Add tools to PATH
          echo "${HOME}/.cargo/bin" >> $GITHUB_PATH
          
          # Make binaries executable
          find ./artifacts -name "*parachain*" -type f -exec chmod +x {} \;
          
          # Verify tools are available
          chain-spec-builder --version
          polkadot-omni-node --version

      - name: Generate chain specification
        run: |
          echo "🔧 Generating chain specification..."
          echo "📋 Using repository: ${{ inputs.template-repo }}"
          echo "📋 Using branch: ${{ inputs.template-branch }}"
          
          # Find the runtime WASM file
          RUNTIME_WASM=$(find ./artifacts -name "*.compressed.wasm" -type f | head -1)
          if [ -z "$RUNTIME_WASM" ]; then
            echo "❌ Runtime WASM file not found"
            echo "Available files:"
            find ./artifacts -type f
            exit 1
          fi
          
          echo "✅ Using runtime: $RUNTIME_WASM"
          
          # Generate chain spec
          chain-spec-builder create \
            -t development \
            --relay-chain ${{ inputs.relay-chain }} \
            --para-id ${{ inputs.para-id }} \
            --runtime "$RUNTIME_WASM" \
            named-preset development
          
          # Verify chain spec was created
          if [ ! -f "chain_spec.json" ]; then
            echo "❌ Chain spec generation failed"
            exit 1
          fi
          
          echo "✅ Chain specification generated successfully"
          echo "📄 Chain spec size: $(du -h chain_spec.json | cut -f1)"

      - name: Validate chain specification
        run: |
          echo "🔍 Validating chain specification..."
          
          # Check if it's valid JSON
          if ! jq empty chain_spec.json 2>/dev/null; then
            echo "❌ Invalid JSON in chain specification"
            exit 1
          fi
          
          # Extract key information
          CHAIN_NAME=$(jq -r '.name // "unknown"' chain_spec.json)
          PARA_ID=$(jq -r '.para_id // "unknown"' chain_spec.json)
          RELAY_CHAIN=$(jq -r '.relay_chain // "unknown"' chain_spec.json)
          
          echo "✅ Chain specification is valid"
          echo "📋 Chain Name: $CHAIN_NAME"
          echo "🆔 Para ID: $PARA_ID"
          echo "🔗 Relay Chain: $RELAY_CHAIN"
          echo "📦 Template Source: ${{ inputs.template-repo }}@${{ inputs.template-branch }}"

      - name: Start Polkadot omni-node
        timeout-minutes: 5
        run: |
          echo "🚀 Starting Polkadot omni-node..."
          echo "📦 Built from: ${{ inputs.template-repo }}@${{ inputs.template-branch }}"
          
          # Determine run duration
          RUN_DURATION=${{ inputs.run-duration }}
          if [ "$RUN_DURATION" = "0" ]; then
            echo "⚠️ Running indefinitely (workflow will timeout after 6 hours)"
            TIMEOUT_CMD=""
          else
            echo "⏱️ Running for ${RUN_DURATION} seconds"
            TIMEOUT_CMD="timeout ${RUN_DURATION}s"
          fi
          
          # Start node in background with logging
          $TIMEOUT_CMD polkadot-omni-node \
            --chain ./chain_spec.json \
            --dev \
            --tmp \
            --rpc-cors all \
            --unsafe-rpc-external \
            --rpc-methods unsafe \
            --log info \
            > node.log 2>&1 &
          
          NODE_PID=$!
          echo "NODE_PID=$NODE_PID" >> $GITHUB_ENV
          
          echo "✅ Node started with PID: $NODE_PID"
          
          # Wait a moment for startup
          sleep 10
          
          # Check if node is still running
          if ! kill -0 $NODE_PID 2>/dev/null; then
            echo "❌ Node failed to start"
            echo "📋 Last 50 lines of log:"
            tail -50 node.log
            exit 1
          fi
          
          echo "✅ Node is running successfully"

      - name: Health check and monitoring
        timeout-minutes: 2
        run: |
          echo "🏥 Performing health checks..."
          
          # Monitor node for a short period
          for i in {1..12}; do
            if ! kill -0 $NODE_PID 2>/dev/null; then
              echo "❌ Node stopped unexpectedly"
              echo "📋 Final log output:"
              tail -100 node.log
              exit 1
            fi
            
            echo "✅ Health check $i/12 - Node is running"
            sleep 5
          done
          
          echo "✅ All health checks passed"

      - name: Cleanup
        if: always()
        run: |
          echo "🧹 Cleaning up..."
          
          # Stop the node gracefully
          if [ -n "${NODE_PID:-}" ] && kill -0 $NODE_PID 2>/dev/null; then
            echo "🛑 Stopping node (PID: $NODE_PID)..."
            kill -TERM $NODE_PID
            
            # Wait for graceful shutdown
            for i in {1..10}; do
              if ! kill -0 $NODE_PID 2>/dev/null; then
                echo "✅ Node stopped gracefully"
                break
              fi
              sleep 1
            done
            
            # Force kill if still running
            if kill -0 $NODE_PID 2>/dev/null; then
              echo "⚡ Force stopping node..."
              kill -KILL $NODE_PID
            fi
          fi
          
          echo "✅ Cleanup completed"

      - name: Upload logs
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: node-logs-${{ github.run_id }}
          path: |
            node.log
            chain_spec.json
          retention-days: 7